#!/bin/bash
# Fetches real Singapore public holiday + NUS academic calendar data and
# writes it to a course's config/holidays.conf -- the exact DATE|NAME
# format core/enrich-lib.sh's is_holiday already reads (see that
# function's own comment: fetching a real institution's calendar is
# genuinely institution-specific, so this orchestrator lives here under
# institutions/nus/, not in core/, and core/ doesn't know it exists).
#
# Usage: institutions/nus/fetch-calendar-data.sh [SEMESTER_START_DATE]
# (run with COURSE_ROOT set to the consuming course repo, same
# convention as core/cli.sh)
#
# Reads config/course.mk for COURSE_CODE (used only to also fetch that
# module's exam date from NUSMods -- optional, skipped with a warning if
# COURSE_CODE isn't set or NUSMods has no data for it) and
# SEMESTER_START_MONDAY (used as the fetch year range's basis if no
# SEMESTER_START_DATE argument is given).
#
# What it writes:
#   config/holidays.conf         DATE|NAME -- Singapore public holidays
#                                 + NUS-specific holidays (e.g.
#                                 Well-Being Day) merged. Recess/Reading
#                                 Week are deliberately NOT included here
#                                 -- they're date *ranges*, not single-
#                                 day cancellations; a course's own
#                                 RECESS_AFTER_WEEK in course.mk already
#                                 handles recess placement in the
#                                 schedule.
#   config/calendar-data/*.conf  raw fetch cache (sg-holidays-*,
#                                 nus-calendar-*, exam-*) -- kept for
#                                 reference/debugging, not read by core/
#                                 or by config/holidays.conf's consumers
#                                 directly.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/calendar-data-lib.sh"

COURSE_ROOT="${COURSE_ROOT:-.}"
cd "$COURSE_ROOT"

COURSE_MK="config/course.mk"
course_var() {
    [ -f "$COURSE_MK" ] || return 0
    grep -E "^$1[[:space:]]*=" "$COURSE_MK" | head -1 \
        | sed -E 's/^[A-Za-z_][A-Za-z_0-9]*[[:space:]]*=[[:space:]]*//' || true
}

COURSE_CODE="$(course_var COURSE_CODE)"
START_DATE="${1:-$(course_var SEMESTER_START_MONDAY)}"
START_DATE="${START_DATE:-2026-08-10}"

start_year=$(echo "$START_DATE" | cut -d'-' -f1)
start_month=$(echo "$START_DATE" | cut -d'-' -f2)
end_year=$((start_year + 1))

# NUS's academic year runs Aug(year N) - ~May(year N+1) -- Semester 1
# starts in year N itself, Semester 2 starts in January of year N+1. A
# semester starting Jan-Jul therefore belongs to the academic year that
# STARTED the previous August, not the one starting that same calendar
# year (e.g. a 2026-01-12 Semester 2 start is AY2025-2026, not
# AY2026-2027) -- get this wrong and fetch_nus_calendar_dynamic pulls
# the wrong PDF entirely (different semester's dates).
if [ "$((10#$start_month))" -ge 8 ]; then
    acad_start_year="$start_year"
else
    acad_start_year=$((start_year - 1))
fi
acad_year="${acad_start_year}-$((acad_start_year + 1))"

echo "Fetching calendar data for semester start date: $START_DATE"
echo "Academic year: $acad_year"

SG_HOLIDAYS=()
NUS_SPECIAL_DATES=()

fetch_sg_holidays_dynamic "$start_year" "$end_year"
fetch_nus_calendar_dynamic "$acad_year"
save_calendar_data_cache "$start_year" "$end_year" "$acad_year"

if [ -n "$COURSE_CODE" ]; then
    # Same Aug-vs-Jan split as acad_year above: a semester starting
    # Aug-Dec is NUSMods semester 1, Jan-Jul is semester 2.
    if [ "$((10#$start_month))" -ge 8 ]; then
        nusmods_semester=1
    else
        nusmods_semester=2
    fi
    if fetch_nusmods_exam_dynamic "$COURSE_CODE" "$acad_year" "$nusmods_semester"; then
        save_exam_cache "$acad_year" "$COURSE_CODE"
    else
        echo " - Warning: could not fetch $COURSE_CODE exam date from NUSMods; leaving any cached exam data as-is." >&2
    fi
else
    echo " - No COURSE_CODE set in $COURSE_MK; skipping NUSMods exam-date fetch." >&2
fi

HOLIDAYS_FILE="config/holidays.conf"
mkdir -p "$(dirname "$HOLIDAYS_FILE")"
{
    echo "# Singapore public holidays + NUS-specific holidays (e.g. Well-Being"
    echo "# Day), merged. Generated by tooling/institutions/nus/fetch-calendar-data.sh"
    echo "# -- do not hand-edit, re-run the script instead. Format: DATE|NAME."
    printf '%s\n' "${SG_HOLIDAYS[@]}" | sort -u
} > "$HOLIDAYS_FILE"
echo " - Wrote ${#SG_HOLIDAYS[@]} holidays to $HOLIDAYS_FILE"

echo "Calendar data updated."
